pipelines:
  - name: pipeOne
    steps:
      - name: stepOne
        type: bash
        configuration:
          cache: false
        setup:
          runtime:
            type: auto
            image:
              auto:
                language: none
        execution:
          onExecute:
            - echo "Hello, World!"
